

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/

  server:
    eviction-interval-timer-in-ms: 1000

spring:
  application:
    name: api-gateway-service
    cloud:
      gateway:
        routes:
          - id: offers-service
            url: lb://OFFER-SERVICE
            predicates:
              -Path=/list/**




